#!/usr/bin/env bash
# installing nginx on web-01

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
