#!/usr/bin/env bash
# installing nginx on web-01

# update the advanced packaging tool
sudo apt-get -y update

# upgrade the advanced packaging tool
sudo apt-get upgrade -y

# install nginx on server
sudo apt-get install nginx -y

# start nginx server
sudo service nginx start

# configure firewall to allow traffic through port 80
sudo ufw allow 'Nginx HTTP'

# give user full ownership to website file
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

# put contents in the index file
echo "Hello World!" > /var/www/html/index.html

# restart nginx
sudo service nginx restart
