#!/usr/bin/env bash
ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"

sudo apt-get -y update
sudo apt-get -y install nginx
#sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx start
