#!/usr/bin/env bash
# installing nginx on web-01

# update the advanced packaging tool
sudo apt-get -y update

# upgrade the advanced packaging tool
sudo apt-get upgrade -y

# install nginx on server
sudo apt-get install nginx -y

# start nginx server
sudo service nginx start

# configure firewall to allow traffic through port 80
sudo ufw allow 'Nginx HTTP'

# give user full ownership to website file
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

# put contents in the index file
echo "Hello World!" > /var/www/html/index.html

# setting up a redirect me configuration
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# setting up 404
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '25i\	error_page 404 /404.html;' /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart
