#!/usr/bin/env bash
# installing nginx on web-01

# update the advanced packaging tool
sudo apt-get -y update

# upgrade the advanced packaging tool
sudo apt-get upgrade -y

# install nginx on server
sudo apt-get install nginx -y

# start nginx server
sudo service nginx start

# configure firewall to allow traffic through port 80
sudo ufw allow 'Nginx HTTP'

# give user full ownership to website file
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

# put contents in the index file
echo "Hello World!" > /var/www/html/index.html

# setting up 404
echo "Ceci n'est pas une page" > /var/www/html/404.html

# server configuration
server_config=\
"server {
		listen 80 default_server;
		listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html
		server_name_;
		add_header X-Served-By \$hostname;

		location / {
			try_files \$uri \$uri/ =404;
		}
		if (\$request_filename ~ redirect_me){
			rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
		}
		error_page 404 /404.html;
		location = /404.html {
			internal;
		}
}"

echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
