#!/usr/bin/env bash
# configure Nginx on a web server: web-02

# installing the web server Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

sudo mkdir -p /var/www/html
sudo chown -R $USER:$USER /var/www
touch /var/www/html/index.html
# put some text in the index files
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# change permision for default file
sudo chmod 777 /etc/nginx/sites-available/default

# configure the server: web-02
print %s "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME

    root /var/www/html;
    index index.com index.htm;
    location /redirect_me {
        return 301 http://www.google.com/;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
