#!/usr/bin/env bash
# Installs and configures load balancer

sudo apt-get -y update
sudo apt-get -y upgrade
apt-get -y install haproxy
server_config=\
"
frontend  siphamandla-frontend
        bind *:80
        mode http
        default_backend siphamandla-backend
backend siphamandla-backend
        balance roundrobin
        server 102332-web-01 100.26.20.241:80 check
        server 102332-web-02 54.144.240.136:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
