#!/usr/bin/env bash
#Purpose: Prints out the PID of the current process.
#Version: 1.0
#Created date:  Tue Oct 3 00:45:27 SAST 2023
#Modified date: None.
#Author: Siphamandla Matshiane

# START #
echo $$
# END #
