#!/usr/bin/env bash
#Purpose: Print out information about all running processes.
#Version: 1.0
#Created date:  Tue Oct 3 00:49:05 SAST 2023
#Modified date: None.
#Author: Siphamandla Matshiane

# START #
ps -auxf
# END #
