#!/usr/bin/env bash
#Purpose: displays "To infinity and beyond" indefinitely.
#Version: 1.0
#Created date:  Tue Oct 3 01:07:29 SAST 2023
#Modified date: None.
#Author: Siphamandla Matshiane

# START #
while true
do
	echo "To infinity and beyond"
	sleep 2
done
# END #
