#!/usr/bin/env bash
#Purpose: Kills a process.
#Version: 1.0
#Created date:  Tue Oct 3 01:14:43 SAST 2023
#Modified date: None.
#Author: Siphamandla Matshiane

# START #
kill "$(pgrep -f "4-to_infinity_and_beyond")"
# END #
