#!/usr/bin/env bash
#Purpose: Kill another process in a different terminal.
#Version: 1.0
#Created date:  Tue Oct 3 01:21:16 SAST 2023
#Modified date: None.
#Author: Siphamandla Matshiane

# START #
pkill -f "4-to_infinity_and_beyond"
# END #
