#!/usr/bin/env bash
#Purpose: Kills another on going process.
#Version: 1.0
#Created date:  Tue Oct 3 01:29:02 SAST 2023
#Modified date: None.
#Author: Siphamandla Matshiane

# START #
pkill -f "7-highlander"
# END #
