#!/usr/bin/env bash
#Purpose: Using trap.
#Version: 1.0
#Created date:  Tue Oct 3 01:24:34 SAST 2023
#Modified date: None.
#Author: Siphamandla Matshiane

# START #
trap "echo \"I am invincible!!!\"" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
# END #
