#!/usr/bin/env bash
#Purpose: Kills another process.
#Version: 1.0
#Created date:  Tue Oct 3 01:33:24 SAST 2023
#Modified date: None.
#Author: Siphamandla Matshiane

# START #
pkill -KILL -f "7-highlander"
# END #
