#!/usr/bin/env bash
#Purpose: Print Best school using a for loop
#Version: 1.0
#Created date:  Mon Oct 2 14:21:50 SAST 2023
#Modified date: None
#Author: Siphamandla Matshiane

# START #
for _ in {1..10}
do
	echo "Best School"
done
# END #
