#!/usr/bin/env bash
#Purpose: Displays contents of the /etc/passwd
#Version: 1.0
#Created date:  Mon Oct 2 19:22:35 SAST 2023
#Modified date: None
#Author: Siphamandla Matshiane

# START #
FILE="/etc/passwd"
while read -r LINE
do
	echo "$LINE" | cut -d ":" -f 1,3,6
done < $FILE
# END #
