#!/usr/bin/env bash
#Purpose: Display contents of the file /etc/passwd
#Version: 1.0
#Created date:  Mon Oct 2 19:47:02 SAST 2023
#Modified date: None
#Author: Siphamandla Matshiane

# START #
FILE="/etc/passwd"
while IFS=":" read -r usr pw uid gid uinfo homedir shell
do
    echo "The user $usr is part of the $gid gang, lives in $homedir and \
rides $shell. $uid's place is protected by the passcode $pw, \
more info about the user here: $uinfo"
done < "$FILE"
# END #
