#!/usr/bin/env bash
#Purpose: Prints out Best school using a while loop.
#Version: 1.0
#Created date:  Mon Oct 2 16:10:29 SAST 2023
#Modified date: None
#Author: Siphamandla Matshiane

# START #
COUNT=1
while [ $COUNT -le 10 ]
do
	echo "Best School"
	COUNT=$(( COUNT + 1 ))
done
# END #
