#!/usr/bin/env bash
#Purpose: Print Best School using until loop.
#Version: 1.0
#Created date:  Mon Oct 2 16:37:40 SAST 2023
#Modified date: None
#Author: Siphamandla Matshiane

# START #
COUNT=1
until [ $COUNT -gt 10 ]
do
	echo "Best School"
	COUNT=$(( COUNT + 1 ))
done
# END #
