#!/usr/bin/env bash
#Purpose: Conditional printing.
#Version: 1.0
#Created date:  Mon Oct 2 16:45:07 SAST 2023
#Modified date: None.
#Author: Siphamandla Matshiane

# START #
COUNT=1
while [ $COUNT -le 10 ]
do
	echo "Best School"
	if [ $COUNT -eq 9 ]
	then
		echo "Hi"
	fi
	COUNT=$(( COUNT + 1 ))
done
# END #
