#!/usr/bin/env bash
#Purpose: Conditional Printing.
#Version: 1.0
#Created date:  Mon Oct 2 16:58:33 SAST 2023
#Modified date: None.
#Author: Siphamandla Matshiane

# START #
COUNT=1
while [ $COUNT -le 20 ]
do
	echo "$COUNT"
	case $COUNT in
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
	COUNT=$(( COUNT + 1))
done
# END #
