#!/usr/bin/env bash
#Purpose: Conditional Printing.
#Version: 1.0
#Created date:  Mon Oct 2 16:58:33 SAST 2023
#Modified date: None.
#Author: Siphamandla Matshiane

# START #
COUNT=1
while [ $COUNT -le 20 ]
do
	echo "$COUNT"
	if [ $COUNT -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $COUNT -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $COUNT -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	COUNT=$(( COUNT + 1))
done
# END #
