#!/usr/bin/env bash
#Purpose: Displays time
#Version: 1.0
#Created date:  Mon Oct 2 17:13:17 SAST 2023
#Modified date: None
#Author: Siphamandla Matshiane

# START #
HOUR=0
while [ $HOUR -le 12 ]
do
	echo "Hour: $HOUR"
	MIN=1
	while [ $MIN -le 59 ]
	do
		echo "$MIN"
		MIN=$(( MIN + 1 ))
	done
	HOUR=$(( HOUR + 1))
done
# END #
