#!/usr/bin/env bash
#Purpose: List everything in the current directory.
#Version: 1.0
#Created date:  Mon Oct 2 17:29:18 SAST 2023
#Modified date: None.
#Author: Siphamandla Matshiane

# START #
FILES=$(ls)
for file in $FILES
do
	echo "$file" | cut -d "-" -f 2
done
# END #
