#!/usr/bin/env bash
#Purpose: Gives information about a file.
#Version: 1.0 
#Created date:  Mon Oct 2 17:36:56 SAST 2023
#Modified date: None
#Author: Siphamandla Matshiane

# START #
FILE="school"
if [ -e $FILE ]
then
	echo "school file exists"
	if [ -s $FILE ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $FILE ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
# END #
