#!/usr/bin/env bash
# Configures an Ubuntu server by resolving
# a localhost to 127.0.0.2 and facebook.com
# to 8.8.8.8

# START HERE
cp /etc/hosts ~/hosts.new
sed -i "s/.*localhost$/127.0.0.2    localhost/g" ~/hosts.new
sed -i "s/.*facebook.com//g" ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
# END OF SCRIPT
